### Numpy 연습문제3

In [35]:
import numpy as np

### 연습문제. 마스크 인덱싱

In [34]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo',
                  'Park','Beomwoo'])
data = np.random.randn(8,4)  # 표준정규분포난수

In [36]:
data

array([[-0.40618165,  0.3280674 , -0.37119806, -1.11285073],
       [-1.9986285 , -0.90069215, -0.44198883,  0.12862539],
       [-1.71602106, -0.75255992,  0.98789371,  0.61172768],
       [ 0.35799252, -1.49675036, -0.23253812,  1.14107112],
       [-2.15933824, -0.19889371, -0.93168989,  0.06366116],
       [ 0.18355602, -0.76731819,  0.68241964, -1.49308159],
       [-0.9375372 , -0.24631064, -0.44128999,  0.8117707 ],
       [-0.50192211,  1.38010133, -1.41740265, -0.27303674]])

#### 문제1. data array에서 0번째 열이 0보다 작은 행 데이터 가져오기

In [37]:
arr = data[:,0]
data[arr < 0, 0]

array([-0.40618165, -1.9986285 , -1.71602106, -2.15933824, -0.9375372 ,
       -0.50192211])

#### 문제2. data array에서 0번째 열이 0보다 작은 행의 2, 3번째 열 데이터 가져오기

In [42]:
arr = data[:,0]
arr1 = data[arr < 0, 1:3]
arr1

array([[ 0.3280674 , -0.37119806],
       [-0.90069215, -0.44198883],
       [-0.75255992,  0.98789371],
       [-0.19889371, -0.93168989],
       [-0.24631064, -0.44128999],
       [ 1.38010133, -1.41740265]])

----------------------------------------------

### 연습문제: 정렬

In [43]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

#### 문제1. 위 행렬에서 성적의 오름차순으로 학생의 이름을 출력하시오.

In [44]:
name_array[np.argsort(score_array)]

array(['John', 'Sarah', 'Samuel', 'Mike', 'Kate'], dtype='<U6')

#### 문제2. 성적이 가장 좋은 사람의 이름을 출력하시오

In [30]:
name_array[np.argmax(score_array)]

'Kate'