# 임베딩(embedding)

### 카운트 벡터화 실습

In [1]:
import sklearn
sklearn.__version__

'1.2.2'

#### 텍스트 데이터

In [2]:
text_sample_01 = 'The Matrix is everywhere its all around us, here even in this room. \
You can see it out your window or on your television. \
You feel it when you go to work, or go to church or pay your taxes.'

text_sample_02 = 'You take the blue pill and the story ends.\
You wake in your bed and you believe whatever you want to believe\
You take the red pill and you stay in Wonderland and I show you how deep the rabbit-hole goes.'

In [4]:
text = []
text.append(text_sample_01)
text.append(text_sample_02)
text

['The Matrix is everywhere its all around us, here even in this room. You can see it out your window or on your television. You feel it when you go to work, or go to church or pay your taxes.',
 'You take the blue pill and the story ends.You wake in your bed and you believe whatever you want to believeYou take the red pill and you stay in Wonderland and I show you how deep the rabbit-hole goes.']

#### CountVectorizer객체 생성 후 fit()으로 단어사전 생성

In [5]:
from sklearn.feature_extraction.text import CountVectorizer 

In [6]:
cnt_vect = CountVectorizer()
cnt_vect.fit(text)

CountVectorizer()

#### 생성된 단어사전 확인 :  `vocabulary_` 속성

In [8]:
# word_index와 비슷하나 인덱스 매핑 기준은 알파벳 순서
print(cnt_vect.vocabulary_)

{'the': 39, 'matrix': 23, 'is': 20, 'everywhere': 12, 'its': 22, 'all': 0, 'around': 2, 'us': 42, 'here': 16, 'even': 11, 'in': 19, 'this': 40, 'room': 31, 'you': 50, 'can': 7, 'see': 32, 'it': 21, 'out': 26, 'your': 51, 'window': 47, 'or': 25, 'on': 24, 'television': 38, 'feel': 13, 'when': 46, 'go': 14, 'to': 41, 'work': 49, 'church': 8, 'pay': 27, 'taxes': 37, 'take': 36, 'blue': 6, 'pill': 28, 'and': 1, 'story': 35, 'ends': 10, 'wake': 43, 'bed': 3, 'believe': 4, 'whatever': 45, 'want': 44, 'believeyou': 5, 'red': 30, 'stay': 34, 'wonderland': 48, 'show': 33, 'how': 18, 'deep': 9, 'rabbit': 29, 'hole': 17, 'goes': 15}


In [9]:
len(cnt_vect.vocabulary_)

52

#### 데이터 적용하여 피처벡터화

In [10]:
# transform -> 피처벡터화 -> 중복된 단어를 제외하고 여러 문서를 합쳐 count 벡터화
ftr_mat = cnt_vect.transform(text)
ftr_mat

<2x52 sparse matrix of type '<class 'numpy.int64'>'
	with 57 stored elements in Compressed Sparse Row format>

#### 피처 벡터화 후 데이터 유형 및 여러 속성 확인

In [12]:
ftr_mat.toarray()

array([[1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 2, 0, 1, 0, 0, 1, 1, 2,
        1, 1, 1, 3, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 2, 1, 0,
        0, 0, 1, 1, 0, 1, 3, 3],
       [0, 4, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 2, 0, 0,
        0, 0, 0, 0, 0, 0, 2, 1, 1, 0, 0, 1, 1, 1, 2, 0, 0, 4, 0, 1, 0, 1,
        1, 1, 0, 0, 1, 0, 6, 1]], dtype=int64)

#### 빈도가 높은 5개 피처만 갖도록 카운트 벡터화

In [13]:
cnt_vect = CountVectorizer(max_features=5)
cnt_vect.fit(text)
ftr_mat = cnt_vect.transform(text)
print(type(ftr_mat))
print(f'크기', ftr_mat.shape)
print(f'단어집합(사전)', cnt_vect.vocabulary_)

<class 'scipy.sparse._csr.csr_matrix'>
크기 (2, 5)
단어집합(사전) {'the': 1, 'you': 3, 'your': 4, 'to': 2, 'and': 0}


#### ngram_range를 적용한 카운트 벡터화

- ngram_range=(1,3) : 단어 1개씩 토큰화하고 순서대로 연속된 3개 단어를 묶어서 피처화

##### ngram_range=(1,3) -> 단어 1개씩, 2개씩, 3개씩 뭉쳐서 표현
- "고양이는 창문을 통해 나가고 싶어합니다." -> 
- (1-gram): "고양이는", "창문을", "통해", "나가고", "싶어합니다."
- (2-gram): "고양이는 창문을", "창문을 통해", "통해 나가고", "나가고 싶어합니다."
- (3-gram): "고양이는 창문을 통해", "창문을 통해 나가고", "통해 나가고 싶어합니다."

In [20]:
cnt_vect = CountVectorizer(ngram_range=(1,3))
cnt_vect.fit(text)
ftr_mat = cnt_vect.transform(text)
print(type(ftr_mat))
print(f'크기', ftr_mat.shape)
print(f'단어집합(사전)', cnt_vect.vocabulary_)

<class 'scipy.sparse._csr.csr_matrix'>
크기 (2, 202)
단어집합(사전) {'the': 130, 'matrix': 78, 'is': 67, 'everywhere': 41, 'its': 75, 'all': 0, 'around': 11, 'us': 151, 'here': 52, 'even': 38, 'in': 60, 'this': 141, 'room': 107, 'you': 175, 'can': 26, 'see': 110, 'it': 70, 'out': 91, 'your': 194, 'window': 166, 'or': 84, 'on': 81, 'television': 127, 'feel': 44, 'when': 163, 'go': 47, 'to': 144, 'work': 172, 'church': 29, 'pay': 94, 'taxes': 126, 'the matrix': 133, 'matrix is': 79, 'is everywhere': 68, 'everywhere its': 42, 'its all': 76, 'all around': 1, 'around us': 12, 'us here': 152, 'here even': 53, 'even in': 39, 'in this': 61, 'this room': 142, 'room you': 108, 'you can': 178, 'can see': 27, 'see it': 111, 'it out': 71, 'out your': 92, 'your window': 200, 'window or': 167, 'or on': 87, 'on your': 82, 'your television': 198, 'television you': 128, 'you feel': 180, 'feel it': 45, 'it when': 73, 'when you': 164, 'you go': 182, 'go to': 48, 'to work': 149, 'work or': 173, 'or go': 85, 'to ch

In [15]:
ftr_mat.toarray()

array([[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 2, 2, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
        0, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 3,
        0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 1,
        1, 1, 1, 1],
       [0, 0, 0, 4, 1, 1, 1, 1, 2, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 2, 0, 0, 1, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 

#### 한글텍스트에 대한 카운트 벡터화

In [21]:
text2 = ['나는 배가 고프다', '내일 점심 뭐먹지','내일 공부해야겠다','점심 먹고 공부해야지']

cnt_vect = CountVectorizer()
cnt_vect.fit(text2)
ftr_mat = cnt_vect.transform(text2)
print(type(ftr_mat))
print(f'크기', ftr_mat.shape)
print(f'단어집합(사전)', cnt_vect.vocabulary_)

<class 'scipy.sparse._csr.csr_matrix'>
크기 (4, 9)
단어집합(사전) {'나는': 3, '배가': 7, '고프다': 0, '내일': 4, '점심': 8, '뭐먹지': 6, '공부해야겠다': 1, '먹고': 5, '공부해야지': 2}


In [22]:
ftr_mat.toarray()

array([[1, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 1]], dtype=int64)

### TF-IDF 피처벡터화 실습

#### 유사도 행렬 계산
- 문장 간의 유사도 계산

#### COO, CSR 표현 실습

----------